language: erlang
matrix:
  include:
    - os: linux
      otp_release: 21.1
    - os: linux
      otp_release: 20.3.8.5
    - os: linux
      otp_release: 19.3
    - os: osx
      language: generic
dist: xenial
addons:
  apt:
    packages:
      - g++
      - make
      - cmake
      - libuv1-dev
      - libssl-dev
before_script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ $TRAVIS_OS_NAME == osx ]]; then brew install erlang libuv cmake openssl; fi
script:
    - rebar3 compile
