os:
- linux
- osx
dist: xenial
addons:
  apt:
    packages:
      - g++
      - make
      - cmake
      - libuv1-dev
      - libssl-dev
language: erlang
otp_release:
    - 21.1
    - 20.3.8.5
    - 19.3
before_script:
- if [[ $TRAVIS_OS_NAME == osx ]]; then brew install libuv cmake openssl; fi
script:
    - rebar3 compile
